/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/join`; params?: Router.UnknownInputParams; } | { pathname: `/signin`; params?: Router.UnknownInputParams; } | { pathname: `/../prodev-mobile-app-0x04/_join`; params?: Router.UnknownInputParams; } | { pathname: `/../prodev-mobile-app-0x04/_mainstyle`; params?: Router.UnknownInputParams; } | { pathname: `/../prodev-mobile-app-0x04/app/index`; params?: Router.UnknownInputParams; } | { pathname: `/../prodev-mobile-app-0x04/app/join`; params?: Router.UnknownInputParams; } | { pathname: `/../prodev-mobile-app-0x04/app/signin`; params?: Router.UnknownInputParams; } | { pathname: `/../_join`; params?: Router.UnknownInputParams; } | { pathname: `/../prodev-mobile-app-0x04/constants/index`; params?: Router.UnknownInputParams; } | { pathname: `/../_mainstyle`; params?: Router.UnknownInputParams; } | { pathname: `/../constants/index`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/join`; params?: Router.UnknownOutputParams; } | { pathname: `/signin`; params?: Router.UnknownOutputParams; } | { pathname: `/../prodev-mobile-app-0x04/_join`; params?: Router.UnknownOutputParams; } | { pathname: `/../prodev-mobile-app-0x04/_mainstyle`; params?: Router.UnknownOutputParams; } | { pathname: `/../prodev-mobile-app-0x04/app/index`; params?: Router.UnknownOutputParams; } | { pathname: `/../prodev-mobile-app-0x04/app/join`; params?: Router.UnknownOutputParams; } | { pathname: `/../prodev-mobile-app-0x04/app/signin`; params?: Router.UnknownOutputParams; } | { pathname: `/../_join`; params?: Router.UnknownOutputParams; } | { pathname: `/../prodev-mobile-app-0x04/constants/index`; params?: Router.UnknownOutputParams; } | { pathname: `/../_mainstyle`; params?: Router.UnknownOutputParams; } | { pathname: `/../constants/index`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/join${`?${string}` | `#${string}` | ''}` | `/signin${`?${string}` | `#${string}` | ''}` | `/../prodev-mobile-app-0x04/_join${`?${string}` | `#${string}` | ''}` | `/../prodev-mobile-app-0x04/_mainstyle${`?${string}` | `#${string}` | ''}` | `/../prodev-mobile-app-0x04/app/index${`?${string}` | `#${string}` | ''}` | `/../prodev-mobile-app-0x04/app/join${`?${string}` | `#${string}` | ''}` | `/../prodev-mobile-app-0x04/app/signin${`?${string}` | `#${string}` | ''}` | `/../_join${`?${string}` | `#${string}` | ''}` | `/../prodev-mobile-app-0x04/constants/index${`?${string}` | `#${string}` | ''}` | `/../_mainstyle${`?${string}` | `#${string}` | ''}` | `/../constants/index${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/join`; params?: Router.UnknownInputParams; } | { pathname: `/signin`; params?: Router.UnknownInputParams; } | { pathname: `/../prodev-mobile-app-0x04/_join`; params?: Router.UnknownInputParams; } | { pathname: `/../prodev-mobile-app-0x04/_mainstyle`; params?: Router.UnknownInputParams; } | { pathname: `/../prodev-mobile-app-0x04/app/index`; params?: Router.UnknownInputParams; } | { pathname: `/../prodev-mobile-app-0x04/app/join`; params?: Router.UnknownInputParams; } | { pathname: `/../prodev-mobile-app-0x04/app/signin`; params?: Router.UnknownInputParams; } | { pathname: `/../_join`; params?: Router.UnknownInputParams; } | { pathname: `/../prodev-mobile-app-0x04/constants/index`; params?: Router.UnknownInputParams; } | { pathname: `/../_mainstyle`; params?: Router.UnknownInputParams; } | { pathname: `/../constants/index`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
